# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb323c834e0936fdbc03fb2b6f0a833008e68bdc400b60fc32ecd01d5589b5e4dc4b8963f6a053b944d6cf7624ca8458554f5a32207043686a1f49cd2d05344c

test:
  secret_key_base: 92608c304bd26b9904acad26121e90058b49157901d62a540734e3fedfe0758681387d46af895e3035fe26bb8da768e723a866967be22b523bc69a6948214bf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
